### ISSUE TITLE
Take meta data into consideration when recommending reviewers

### ISSUE THREAD

**Issue by chrisma** [chrisma/marvin#11]
- [ ] It should be possible to discount the line that was added a long time ago in contrast to a line with a more recent commit.

- [ ] It should be possible to discriminate by filetype or folder

- [ ] Rate types of change, e.g. deletion counts double insert

**Comment by tbjoern** [comment]
see marvin.py::Marvin::relevanceOfChange

add command line arguments?
-> see marvin.py::main
